package datasource

import "tonovel/datamodels"

var BookSources = map[int64]datamodels.BookSource{
	1: {
		SourceName: "酷小说",
		SourceURL: "https://www.kuxiaoshuo.com",
		SourceKey: "kuxiaoshuo",

		SearchURL: "https://www.kuxiaoshuo.com/modules/article/search.php?searchkey=%s",
		SearchItemRule: "//tbody/tr[1]/following-sibling::tr",
		SearchItemNameRule: "./td[1]/a/text()",
		SearchItemAuthorRule: "./td[3]/text()",
		SearchItemCoverRule: "",
		SearchItemCategoryRule: "",
		SearchItemNewChapterRule: "./td[2]/a/text()",
		SearchItemURLRule: "./td[1]/a/@href",

		DetailBookNameRule: `//div[@id="info"]/h1/text()`,
		DetailBookAuthorRule: `//div[@id="info"]/p[1]/text()`,
		DetailBookCoverRule: `//div[@id="fmimg"]/img/@src`,
		DetailBookCategoryRule: `//div[@class="con_top"]/a[2]/text()`,
		DetailBookDescriptionRule: `//div[@id="intro"]/p[1]`,
		DetailChapterListURLRule: "",
		DetailNewChapterRule: `//table[@id="adt2"]/parent::div/preceding-sibling::dd`,
		DetailNewChapterTitleRule: `./a/text()`,
		DetailNewChapterURLRule: `./a/@href`,
		DetailChapterRule: `//dt[2]/following-sibling::dd`,
		DetailChapterTitleRule: `./a/text()`,
		DetailChapterURLRule: `./a/@href`,

		ContentTitleRule: `//div[@class="bookname"]/h1/text()`,
		ContentTextRule: `//div[@id="content"]`,
		ContentPreviousURLRule: `//div[@class="bottem1"]/a[2]/@href`,
		ContentNextURLRule: `//div[@class="bottem1"]/a[4]/@href`,
	},
	2: {
		SourceName: "笔趣阁",
		SourceURL: "http://www.biquge.info",
		SourceKey: "biquge",

		SearchURL: "http://www.biquge.info/modules/article/search.php?searchkey=%s",
		SearchItemRule: "//tbody/tr[1]/following-sibling::tr",
		SearchItemNameRule: "./td[1]/a/text()",
		SearchItemAuthorRule: "./td[3]/text()",
		SearchItemCoverRule: "",
		SearchItemCategoryRule: "",
		SearchItemNewChapterRule: "./td[2]/a/text()",
		SearchItemURLRule: "./td[1]/a/@href",
		DetailBookNameRule: `//div[@id="info"]/h1/text()`,
		DetailBookAuthorRule: `//div[@id="info"]/p[1]/text()`,
		DetailBookCoverRule: `//div[@id="fmimg"]/img/@src`,
		DetailBookCategoryRule: `//div[@class="con_top"]/a[2]/text()`,
		DetailBookDescriptionRule: `//div[@id="intro"]/p[1]`,
		DetailChapterListURLRule: "",
		DetailNewChapterRule: "",
		DetailNewChapterTitleRule: "",
		DetailNewChapterURLRule: "",
		DetailChapterRule: `//div[@id="list"]/dl/dd`,
		DetailChapterTitleRule: `./a/text()`,
		DetailChapterURLRule: `./a/@href`,

		ContentTitleRule: `//div[@class="bookname"]/h1/text()`,
		ContentTextRule: `//div[@id="content"]`,
		ContentPreviousURLRule: `//div[@class="bottem1"]/a[2]/@href`,
		ContentNextURLRule: `//div[@class="bottem1"]/a[4]/@href`,
	},
	3: {
		SourceName: "笔趣阁【vipzw】",
		SourceURL: "http://www.vipzw.com",
		SourceKey: "vipzw",
		SearchURL: "http://www.vipzw.com/search.php?searchkey=%s",
		SearchItemRule: `//div[@class="item"]`,
		SearchItemNameRule: ".//dt/a/text()",
		SearchItemAuthorRule: ".//dt/span/text()",
		SearchItemCoverRule: ".//img/@src",
		SearchItemCategoryRule: "",
		SearchItemNewChapterRule: "",
		SearchItemURLRule: ".//dt/a/@href",

		DetailBookNameRule: `//div[@id="info"]/h1/text()`,
		DetailBookAuthorRule: `//div[@id="info"]/p[1]/text()`,
		DetailBookCoverRule: `//div[@id="fmimg"]/img/@src`,
		DetailBookCategoryRule: `//div[@class="con_top"]/a[2]/text()`,
		DetailBookDescriptionRule: `//div[@id="intro"]/p[1]`,
		DetailChapterListURLRule: "",
		DetailNewChapterRule: `//table[@id="adt2"]/parent::div/preceding-sibling::dd`,
		DetailNewChapterTitleRule: `./a/text()`,
		DetailNewChapterURLRule: `./a/@href`,
		DetailChapterRule: `//dt[2]/following-sibling::dd`,
		DetailChapterTitleRule: `./a/text()`,
		DetailChapterURLRule: `./a/@href`,

		ContentTitleRule: `//div[@class="bookname"]/h1/text()`,
		ContentTextRule: `//div[@id="content"]`,
		ContentPreviousURLRule: `//div[@class="bottem1"]/a[2]/@href`,
		ContentNextURLRule: `//div[@class="bottem1"]/a[4]/@href`,
	},
}